name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Move source folder stuff to root folder
      run: cp -R ./src/* ./
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag division42llc-dotnet-webca:$(date +%s)
