name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Move source folder stuff to root folder
      run: cp -R ./src/* ./
    - name: Generate Tag String
      run: echo "docker.pkg.github.com/shawngmc/division42llc-dotnet-webca/division42llc-dotnet-webca:branchname-$branch-$(date +%s)" >> ./tagname
      env:
        branch: ${{GITHUB_REF}} 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $(cat ./tagname)
    - name: Login to publish package
      run: docker login docker.pkg.github.com -u shawngmc -p ${{secrets.GITHUB_TOKEN}} 
    - name: Publish image
      run: docker push $(cat ./tagname)
    - name: Logout
      run: docker logoff
